[theme]
theme = "dracula"
[icons]
icons = "awesome4"

[[block]]
block = "music"
player = "spotify"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 5.0
alert = 2.0

[[block]]
block = "memory"
#display_type = "memory"
#format_mem = "{mem_used_percents}"
#format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "$icon  $percentage $time"

[[block]]
block = "time"
interval = 5

[block.format]
full = "$icon $timestamp.datetime(f:'%a %d/%m %R', l:fr_FR)"
short = "$icon $timestamp.datetime(f:%R)"
