#!/bin/sh

# Absolute path to this script
SCRIPT=`readlink -f $0`
# Absolute path this script is in
SCRIPTPATH=`dirname $SCRIPT`

echo "Linking config files from $SCRIPTPATH"

link (){
    FROM="$SCRIPTPATH/../$1"
    TO=$2

    printf "ln -s %s %s\n" $FROM $TO

    rm $TO
    ln -s $FROM $TO
}

link tigrc ~/.tigrc
link gitconfig ~/.gitconfig
link xinitrc ~/.xinitrc
link Xresources ~/.Xresources
link zshrc ~/.zshrc
link scripts ~/.scripts
mkdir -p ~/.i3/
link i3/config ~/.i3/config
link alacritty/ ~/.config/alacritty
link picom.conf ~/.config/picom.conf
link nvim ~/.config/nvim
link rofi ~/.config/rofi
