#!/bin/sh

# Absolute path to this script
SCRIPT=`readlink -f $0`
# Absolute path this script is in
SCRIPTPATH=`dirname $SCRIPT`

echo "Linking config files from $SCRIPTPATH"

link (){
    FROM="$SCRIPTPATH/../$1"
    TO=$2

    printf "ln -s %s %s\n" $FROM $TO

    rm $TO
    ln -s $FROM $TO
}

link tigrc ~/.tigrc
link gitconfig ~/.gitconfig
link vim ~/.vim
link vim/vimrc ~/.vimrc
link xcolors ~/.xcolors
link xinitrc ~/.xinitrc
link Xresources ~/.Xresources
link zshrc ~/.zshrc
link weechat ~/.weechat
link tmux ~/.tmux
link tmux/tmux.conf ~/.tmux.conf
link scripts ~/.scripts
mkdir -p ~/.config/solarized/
link colors.ini ~/.config/solarized/colors.ini
mkdir -p ~/.i3/
mkdir -p ~/.config/i3status
link i3/config ~/.i3/config
link i3/statusbar/config ~/.config/i3status/config
link compton.conf ~/.config/compton.conf
