#!/usr/bin/zsh

case $1 in
  "down")   pactl set-sink-volume @DEFAULT_SINK@ -5%;;
  "up")     pactl set-sink-volume @DEFAULT_SINK@ +5%;;
  "toggle") pactl set-sink-mute @DEFAULT_SINK@ toggle;;
  *)
esac
