#!/bin/sh

# requires dmenu-xft, for the font
# https://github.com/Dieterbe/dmenu-solarized

source ${XDG_CONFIG_HOME:-$HOME/.config}/solarized/colors.ini

$(/bin/dmenu_path_c | /home/vjousse/.cabal/bin/yeganesh -- -i -b -nb $base3 -nf $base00 -sb $base2 -sf $orange -fn 'xft:DejaVuSansMono:size=8' -p "Run") &
