#!/bin/sh

# requires dmenu-xft, for the font
# https://github.com/Dieterbe/dmenu-solarized

source ${XDG_CONFIG_HOME:-$HOME/.config}/solarized/colors.ini

$(/bin/dmenu_path_c | /home/vjousse/.cabal/bin/yeganesh -- -i -b -nb $base03 -nf $base0 -sb $base02 -sf $orange -fn 'xft:Inconsolata:size=10' -p "Run") &
