#!/usr/bin/env bash

set -euo pipefail


usage() {
  cat <<EOF
Usage: pomo [OPTIONS] TIMER STRING

Start pomodorolm and log the activity in HOME/.my_pomodoro
Wrapper around: https://github.com/vjousse/pomodorolm  

Arguments:
  TIMER         Number of minutes for a pomodoro (positive integer) not working
  STRING        Text to describe the goal of the pomodoro

Options:
  -h, --help    Display this help message and exit

Examples:
  pomo 25 "My awesome task"
EOF
  exit 0
}

die() {
  local message=$1
  local code=${2:-1}
  echo "Error: $message" >&2
  exit "$code"
}


function main() {
  local timer=25
  
if [ "$#" -ne 2 ]; then
    echo "Nop: pomo 25 \"my task\""
    exit 1
fi

if [ -f ~/.cache/pomodoro_session ]; then
    echo "Nop: pomodorolm is already running"
    exit 1
fi

# timer=$1 # right now do nothing: scaffolding to specify time 
# should be a default
description=$2 
HISTORY=~/.my_pomodoro

if [ -f $HISTORY ]; then
    cat $HISTORY # maybe change to wc since it will grow  
    else 
    echo "Init $HISTORY"
    echo "date; action; description" > $HISTORY
fi

echo "start pomodorolm"
echo "$(date); start; $description;"  >> $HISTORY

my_exit() {
    echo "$(date); end; $description;" >> $HISTORY
} 

trap 'my_exit' EXIT 

pomodorolm 

}

main "$@"
