#!/bin/zsh
# Mostly stolen from http://github.com/ornicar/dotfiles
# 0 black
# 1 red
# 2 green
# 3 yellow
# 4 blue
# 5 pink
# 6 cyan
# 9 orange
# black -> white 8 0 10 11 12 14 7 15 

# BATTERY

infos=$(acpi -b)
percent=$(echo $infos|sed "s/Battery .: [a-z]*, \([0-9]*\)%\(,.*\|$\)/\1/i")
state=$(echo $infos|sed "s/Battery .: \([a-z]*\),.*/\1/i")
if [ "$percent" -lt 5 ]; then modifier="#[bg=colour1,fg=colour15,bright]"
elif [ "$percent" -lt 20 ]; then modifier="#[bg=colour3,fg=colour8,bright]"
elif [ "$percent" -lt 50 ]; then modifier="#[fg=colour3]"
else modifier="#[fg=colour2]"
fi

# Charging status is sometime misdetected on the mac
# Force it when the status is Unknown
if [ "$state" = "Unknown" ]; then state="Charging"
fi

percent="$percent%"

case $state in
    "Charging") sign="|+|"; modifier="#[fg=green]" ;;
    "Discharging") sign="|-|" ;;
    "Full") sign="⚡"; percent= ;;
    *) sign="$state" ;;
esac
printf "$modifier%s%s#[default]" "$percent" "$sign"

# MEMORY

memory=$(free | awk '/buffers\/cache:/ {printf "%.0f", 100*$3/($3 + $4)}')
if [ "$memory" -gt 90 ]; then modifier="#[bg=colour1,fg=colour15,bright]"
elif [ "$memory" -gt 80 ]; then modifier="#[bg=colour3,fg=colour0]"
elif [ "$memory" -gt 70 ]; then modifier="#[fg=colour9]"
else modifier="#[fg=colour2]"
fi
printf " %s%s%%#[default]" "$modifier" "$memory"

# LOAD AVERAGE

load=$(awk '{print $1}' /proc/loadavg)
printf " %s%.01f#[default]" "#[fg=colour14]" "$load"

LANG=fr_FR.UTF-8
printf " #[fg=colour12]⎧$(date +"%a %d %b") $(date +"%H:%M")#[default]"
